apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
      - image: docker.io/cochenj/getting-started:latest
        name: getting-started
        ports:
        - containerPort: 80
